server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** #搜索的微服务路径
    user-service: /user/** #用户微服务
    auth-service: /auth/** # 授权中心微服务
  ignored-services:
      - upload-service # 忽略upload-service服务
  add-host-header: true # 携带域名信息转发
  sensitive-headers:  #覆盖默认敏感头信息，默认zull过滤器中中覆盖了cookie

leyou:
  jwt:
    pubKeyPath: D:\leyou\secret\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item